### ISSUE TITLE
C++ client?

### ISSUE THREAD

**Issue by JFCCoding12** [BISOON/ps4-api-server#4]
any way of making a c++ client so it can be used cross platform? I have been able to connect to the PS4 with c++ but it just disconnects soon after and I can't figure out how to send commands. Any help?

**Comment by 0xwal** [comment]
you can use [Mono Project](https://internationalportal.conestogac.on.ca/InternationalApplication/Content/Login/Login.aspx) cross platform, if you know .net programming you can easily reference the PS4Lib to the project using Mono ide to get it work, regarding the disconnect issue it's because the client ends the connection by closing the app or closing the socket..

good to develop client lib for java which gonna work on all platforms..

**Comment by JFCCoding12** [comment]
Alright thank you, I have started to learn c# and have had no issues with the lib, currently working on an IOS client.
